import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight } from "lucide-react";
import { showcaseCategories, showcaseDesigns } from "@/lib/products/showcase-catalog";

export const metadata = { title: "Wedding & debut invitation designs | Maison de Moments" };

export default function DesignsPage() {
  return <main className="boutique"><header className="boutique-nav"><Link href="/" className="boutique-logo"><span>MM</span>Maison de Moments</Link><nav aria-label="Main navigation"><Link href="/">Home</Link><Link href="/how-to-order">How to order</Link></nav></header>
    <section className="boutique-collection-heading"><p className="boutique-kicker">The invitation collections</p><h1>An invitation as memorable as the day.</h1><p>Discover our finished wedding and debut designs and preview the full guest experience. To ask about ordering, message us through Facebook or Instagram.</p><nav className="boutique-collection-links" aria-label="Invitation categories">{showcaseCategories.map((category) => <a href={`#${category.id}`} key={category.id}>{category.label} <ArrowUpRight size={14} /></a>)}</nav></section>
    {showcaseCategories.map((category) => <section id={category.id} key={category.id} aria-labelledby={`${category.id}-title`} className="boutique-collection"><header className="boutique-collection-title"><p className="boutique-kicker">The {category.id === "debut" ? "debut" : "wedding"} collection</p><h2 id={`${category.id}-title`}>{category.label}</h2><p>{category.description}</p></header><div className="boutique-grid boutique-grid-large">{showcaseDesigns.filter((product) => product.category === category.id).map((product) => <article className="boutique-card" key={product.slug}><Link href={`/designs/${product.slug}`} className="boutique-art" aria-label={`View ${product.name} design`} data-image-treatment={product.imageTreatment}><Image src={product.image} alt="" fill sizes="(max-width: 760px) 100vw, 33vw" /></Link><div><p className="boutique-kicker">{product.categoryLabel} design No. {product.number}</p><h3>{product.name}</h3><p>{product.description}</p><Link href={`/designs/${product.slug}`}>View design and possibilities <ArrowUpRight size={16} /></Link></div></article>)}</div></section>)}
    <section className="boutique-next"><p className="boutique-kicker">More celebrations to come</p><h2>More birthdays and christenings</h2><p>Our designers are creating new collections. Explore the wedding and eighteenth birthday designs above.</p><Link href="/how-to-order" className="boutique-button">Ask about an invitation <ArrowUpRight size={17} /></Link></section></main>;
}
