import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Check } from "lucide-react";
import { weddingProduct, standardTerms } from "@/lib/products/catalog";
import { listPublicOffers } from "@/lib/commerce/offers";
import { ProductView } from "@/components/commerce/product-view";

export default async function DesignPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const product = weddingProduct(slug);
  if (!product) notFound();
  const offers = await listPublicOffers(product.slug);
  return <main className="boutique"><ProductView slug={slug} /><header className="boutique-nav"><Link href="/" className="boutique-logo"><span>MM</span>Maison de Moments</Link><nav aria-label="Main navigation"><Link href="/designs">All designs</Link><Link href="/portal">My invitation</Link></nav></header>
    <section className="boutique-product"><div className="boutique-product-art"><Image src={product.image} alt={`${product.name} artwork preview`} fill priority sizes="(max-width: 850px) 100vw, 50vw" /></div><div className="boutique-product-copy"><Link href="/designs" className="boutique-back"><ArrowLeft size={15} /> All designs</Link><p className="boutique-kicker">Wedding design No. {product.number}</p><h1>{product.name}</h1><p className="boutique-lead">{product.description}</p><p>{product.artworkNote} Names, date, venues, and wording are personalized.</p><Link href={product.preview} className="boutique-button boutique-button-outline" target="_blank">Experience the full sample <ArrowUpRight size={17} /></Link><small>Fictional sample. Sample replies are not submitted.</small></div></section>
    <section className="boutique-intro" id="packages"><p className="boutique-kicker">Choose your level of personalization</p><h2>One design, three ways to make it yours.</h2><p>Every invitation is completed by our team. You review and approve the exact version we publish.</p></section>
    <section className="boutique-tiers">{(["ESSENTIAL", "SIGNATURE", "COUTURE"] as const).map((tier) => { const offer = offers.find((item) => item.tier === tier); return <article key={tier}><p className="boutique-kicker">{tier === "COUTURE" ? "By proposal" : "Full payment at checkout"}</p><h3>{tier[0] + tier.slice(1).toLowerCase()}</h3><p>{tier === "ESSENTIAL" ? "Your names, event details, words, and supported photos in the original design." : tier === "SIGNATURE" ? "Essential plus a curated palette and compatible decorative choices, arranged by our designer." : "A substantial redesign with an agreed brief, deliverables, and timeline."}</p><ul><li><Check size={15} />Designer-finished invitation</li><li><Check size={15} />Private household RSVP</li><li><Check size={15} />Exact-version approval</li></ul>{tier === "COUTURE" ? <Link href={`/designs/${slug}/quote`} className="boutique-button">Request a proposal</Link> : offer?.enabled && offer.priceMinor !== null && offer.turnaroundDays !== null ? <><strong className="boutique-price">{new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(offer.priceMinor / 100)}</strong><p className="boutique-small">Production starts after payment and a complete brief. Typical production: {offer.turnaroundDays} days.</p><Link href={`/checkout?design=${slug}&tier=${tier.toLowerCase()}`} className="boutique-button">Choose {tier.toLowerCase()}</Link></> : <><strong className="boutique-price">Coming soon</strong><p className="boutique-small">Pricing and booking will open when this package is ready.</p></>}</article>; })}</section>
    <section className="boutique-terms"><h2>Included with Essential and Signature</h2><p>{standardTerms.revisionRounds} consolidated design revision rounds · up to {standardTerms.galleryPhotos} photos · up to {standardTerms.households} households · hosting until {standardTerms.hostingDaysAfterEvent} days after the wedding.</p><p>Corrections to facts and errors we introduce do not use a design revision round. Delivery dates, cancellation terms, and applicable tax details are shown before payment.</p></section></main>;
}
