"use client";

import { weddingContentLimits, type WeddingDetails } from "@/lib/products/content";

export function WeddingDetailsFields({ details, onChange }: { details: WeddingDetails; onChange: (details: WeddingDetails) => void }) {
  return <div className="wedding-details-fields">
    <p>These details follow you across the design. Our team checks how every line fits before sharing a review.</p>
    <label>First name as it should appear<input maxLength={120} value={details.preferredNames[0]} onChange={(event) => onChange({ ...details, preferredNames: [event.target.value, details.preferredNames[1]] })} /></label>
    <label>Second name as it should appear<input maxLength={120} value={details.preferredNames[1]} onChange={(event) => onChange({ ...details, preferredNames: [details.preferredNames[0], event.target.value] })} /></label>
    <label>Initials or short monogram<input maxLength={20} value={details.monogram} onChange={(event) => onChange({ ...details, monogram: event.target.value })} placeholder="A & B" /></label>
    <h3>Our story</h3><p>Optional. Leave this empty and the story section disappears cleanly.</p>
    {details.storyChapters.map((chapter, index) => <div className="wedding-repeat" key={index}><label>Chapter heading<input maxLength={120} value={chapter.title} onChange={(event) => onChange({ ...details, storyChapters: details.storyChapters.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item) })} /></label><label>Chapter text<textarea maxLength={600} rows={3} value={chapter.copy} onChange={(event) => onChange({ ...details, storyChapters: details.storyChapters.map((item, itemIndex) => itemIndex === index ? { ...item, copy: event.target.value } : item) })} /></label><button type="button" className="workspace-button secondary" onClick={() => onChange({ ...details, storyChapters: details.storyChapters.filter((_, itemIndex) => itemIndex !== index) })}>Remove chapter</button></div>)}
    {details.storyChapters.length < weddingContentLimits.storyChapters && <button type="button" className="workspace-button secondary" onClick={() => onChange({ ...details, storyChapters: [...details.storyChapters, { title: "", copy: "" }] })}>Add story chapter</button>}
    <h3>Wedding day program</h3><p>Optional. The main ceremony and reception appear automatically.</p>
    {details.program.map((item, index) => <div className="wedding-repeat" key={item.id}><label>Time<input maxLength={40} value={item.time} onChange={(event) => onChange({ ...details, program: details.program.map((entry) => entry.id === item.id ? { ...entry, time: event.target.value } : entry) })} /></label><label>Moment<input maxLength={120} value={item.title} onChange={(event) => onChange({ ...details, program: details.program.map((entry) => entry.id === item.id ? { ...entry, title: event.target.value } : entry) })} /></label><label>Detail<input maxLength={240} value={item.detail} onChange={(event) => onChange({ ...details, program: details.program.map((entry) => entry.id === item.id ? { ...entry, detail: event.target.value } : entry) })} /></label><button type="button" className="workspace-button secondary" onClick={() => onChange({ ...details, program: details.program.filter((_, itemIndex) => itemIndex !== index) })}>Remove moment</button></div>)}
    {details.program.length < weddingContentLimits.programMoments && <button type="button" className="workspace-button secondary" onClick={() => onChange({ ...details, program: [...details.program, { id: crypto.randomUUID(), time: "", title: "", detail: "" }] })}>Add program moment</button>}
    <h3>Entourage</h3><p>Optional. Add groups such as parents, principal sponsors, or attendants.</p>
    {details.entourage.map((group, index) => <div className="wedding-repeat" key={group.id}><label>Group<input maxLength={100} value={group.title} onChange={(event) => onChange({ ...details, entourage: details.entourage.map((entry) => entry.id === group.id ? { ...entry, title: event.target.value } : entry) })} /></label><label>Names, one per line<textarea rows={4} value={group.members.join("\n")} onChange={(event) => onChange({ ...details, entourage: details.entourage.map((entry) => entry.id === group.id ? { ...entry, members: event.target.value.split("\n").slice(0, weddingContentLimits.entourageMembers) } : entry) })} /></label><button type="button" className="workspace-button secondary" onClick={() => onChange({ ...details, entourage: details.entourage.filter((_, itemIndex) => itemIndex !== index) })}>Remove group</button></div>)}
    {details.entourage.length < weddingContentLimits.entourageGroups && <button type="button" className="workspace-button secondary" onClick={() => onChange({ ...details, entourage: [...details.entourage, { id: crypto.randomUUID(), title: "", members: [] }] })}>Add entourage group</button>}
  </div>;
}
